# Generated by Django 4.0.3 on 2022-03-12 15:07

from django.db import migrations, models

import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nte', models.CharField(max_length=6)),
                ('nome', models.CharField(max_length=255)),
                ('gestor', models.CharField(max_length=255)),
                ('telefoneprinc', models.CharField(max_length=255)),
                ('telefonesecun', models.CharField(blank=True, max_length=255)),
                ('emailprinc', models.CharField(max_length=255)),
                ('emailsecun', models.CharField(blank=True, max_length=255)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacao', models.CharField(blank=True, max_length=500)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                                to='contatos.categoria')),
            ],
        ),
    ]
